In [32]:
import numpy as np

In [33]:
# Defining a list:
numberArray = [1,2,3]

In [34]:
# Converting the list to an array. The np.array creates a list to array by taking argument as array.
numberArray = np.array(numberArray)

In [35]:
numberArray

array([1, 2, 3])

In [36]:
# Also a 2-D arrays can be made.
number2DArray = [[1,2], [3,4]]
number2DArray = np.array(number2DArray)

In [37]:
number2DArray

array([[1, 2],
       [3, 4]])

In [38]:
# And 3-D arrays too.
number3DArray = [[[1,2], [3,4]], [[5,6], [7,8]]]
number3DArray = np.array(number3DArray)

In [39]:
number3DArray

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
# To check the dimensions of an array:
# numberArray.ndim
# number2DArray.ndim
number3DArray.ndim

3

In [41]:
# Also we can see the size of an array or num of rows and columns
# numberArray.shape
# number2DArray.shape
number3DArray.shape

(2, 2, 2)

In [43]:
# Checking the datatype stored in numpy array
# NOTE: The numpy array can only store one type of datatype
numberArray.dtype

dtype('int32')

In [47]:
# Getting the total number of elements in the numpy array
number2DArray.size

4