In [1]:
import numpy as np

In [5]:
# Defining a list:
numArray = [[1,2], [3,4]]
numArray = np.array(numArray)

In [6]:
numArray

array([[1, 2],
       [3, 4]])

In [7]:
# Creating an array by defining the datatype while creating
numArrayComp = np.array([[1,2], [3,4]], dtype=complex)

In [8]:
numArrayComp

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
# Creating array using zeros
# It creates an 1D array if argument is a single digit with all values as zero
numArrayZeros = np.zeros(3)
numArrayZeros

array([0., 0., 0.])

In [20]:
# Arrays od 2D and 3D can also been created. Give the value of the number of rows and column in tuple form
numArrayZeros2D = np.zeros((2,4))
numArrayZeros2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# Same we can create array using ones
# This creates an array of 1
numArrayOnes = np.ones(4)
numArrayOnes

array([1., 1., 1., 1.])

In [22]:
# By default the datatype is float64. To get an array of predefined datatype, write the datatype while creating.
numArrayZerosInt = np.zeros((2,3), dtype=np.int16)
numArrayZerosInt

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)